### ISSUE TITLE
Name the App

### ISSUE THREAD

**Issue by diaasaur** [chingu-voyages/v46-tier2-team-14#19]
a fun catchy name if we can come up with it 😭 otherwise something that's not too big or boring

*NOT LIMITED TO ENGLISH*

**Comment by DikshantAgarwal** [comment]
I like name 'RecepieRover'

**Comment by DikshantAgarwal** [comment]
SWAD

**Comment by diaasaur** [comment]
closing this issue if everyone is okay with swad or should it be swaad ?


swaad I think?
