### ISSUE TITLE
As a user, I should be able to see a search bar, so that I know I can search for recipes.

### ISSUE THREAD

**Issue by diaasaur** [chingu-voyages/v46-tier2-team-14#24]

**Comment by DikshantAgarwal** [comment]
Api:- https://tasty.p.rapidapi.com/recipes/list

const options = {
  method: 'GET',
  url: 'https://tasty.p.rapidapi.com/recipes/list',
  params: {
    from: '0',
    size: '20',
    tags: 'under_30_minutes',
    q: 'pizza'
  },

By Default param tags can be under_30_minutes' to show the list of recepies which can be make under 30 minutes.
param q will receive the search item which will enter in the search .i.e pizza

**Comment by diaasaur** [comment]
I think tags is an optional field 🤔 and we should just leave it for now - it doesn't make sense to include external modifiers that the end user hasn't selected themself.
