### ISSUE TITLE
Search Item Select [Integrate with API (recipe/list)]

### ISSUE THREAD

**Issue by DikshantAgarwal** [chingu-voyages/v46-tier2-team-14#36]

**Comment by jdmedlock** [comment]
Description goes here...

**__Dependencies__**:
Parent: #17 
Child:

**__Action Plan__*:
- [ ] Step 1
- [ ] Step 2
- [ ] etc.

**__Acceptance Criteria__**:
- [ ] criteria 1
- [ ] criteria 2
- [ ] etc.
