### ISSUE TITLE
Create Recipe Preview/Summary Component

### ISSUE THREAD

**Issue by DikshantAgarwal** [chingu-voyages/v46-tier2-team-14#37]
- Research what else to include: cooking time, rating, difficulty level
- Check in API what response is flowing in
- #14 

Acceptance Criteria:
- RecipeList rendering list of RecipePreview using grid/flex
- RecipePreview should be a link to `/recipe/id` hardcoded or can be left empty for now until API integration 
- Responsive - Make sure that the list renders good at all common breakpoints (mobile, tablet and desktop)

Sample Data:
- search results for tomato: http://jsonblob.com/1161935675271798784
- in `https://rapidapi.com/apidojo/api/tasty` you can play around with `recipes/list` to check other responses :D

**Comment by diaasaur** [comment]
completed in #51
